### ISSUE TITLE
Replace wget with curl

### ISSUE THREAD

**Issue by rtpro** [JovianX/helm-release-plugin#14]
`wget` is used in the installation process to get `yq`. As `curl` has a wider install-base and comes built in with more systems, we should be using `curl` to pull files instead of `wget`.

**Comment by gangadharjannu** [comment]
Why don't we mention `yq` as a dependency just like `jq` so that we can pre install `yq` before installing this plugin ?

Is there any specific reason why `yq` is being installed manually ?

**Comment by rtpro** [comment]
1. `yq` is not a common package, and in most cases is not present as part of the OS. 
1. `yq` supprots only Snap packaging for Linux, which is not standard in some distros, making it harder to install. 

Because of the above, we decided to ship its binary as part of the plugin installation, implemented by #4 .

**Comment by rtpro** [comment]
Addressed by PR #15 
Thank you @gangadharjannu for the code contribution! 🙏
