### ISSUE TITLE
Enhance OSTYPE environment variable processing during plugin installation 

### ISSUE THREAD

**Issue by vadim-zabolotniy** [JovianX/helm-release-plugin#16]
With last update, where was added automatic installation of `yq`, plugin installation was broken. `echo $OSTYPE` gives `linux-gnu` in  `python:3.10-slim` container.
Currently, during image building facing next error:
```
Unsupported operating system detected while installing yq.
Error: plugin install hook for "release" exited with error
```

**Comment by vadim-zabolotniy** [comment]
My current guess that hook is being executed in `/bin/sh` rather in `/bin/bash`. If I do `echo #OSTYPE` in `sh` I getting nothing.

**Comment by vadim-zabolotniy** [comment]
Here is my [solution](https://github.com/JovianX/helm-release-plugin/pull/17) for this issue.

**Comment by rtpro** [comment]
Thanks, @vadim-zabolotniy, looks good, merged!
