### ISSUE TITLE
I am getting the error 'date: invalid date 'tomorrow'' when setting the TTL for 'tomorrow'

### ISSUE THREAD

**Issue by vilaca** [JovianX/helm-release-plugin#26]
I am getting the error 'date: invalid date 'tomorrow'' when setting the TTL for 'tomorrow'

`helm release ttl "$RELEASE" --set='tomorrow' --namespace "$NAMESPACE"`

**Comment by genisd** [comment]
Please check which `date` binary you are using.
It must be the coreutils implementation.

```
$ date --version
date (GNU coreutils) 8.28
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

**Comment by vilaca** [comment]
Hi, I am no longer using this plugin.

**Comment by vadim-zabolotniy** [comment]
> Please check which `date` binary you are using. It must be the coreutils implementation.
> 
> ```
> $ date --version
> date (GNU coreutils) 8.28
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by David MacKenzie.
> ```

`$ date --version`
date (GNU coreutils) 9.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.

**Comment by genisd** [comment]
that's the on needed and working (for me). the coreutils variant

**Comment by genisd** [comment]
Since OP/issue creator is no longer using the plugin, i suggest we close this.
But it might be worth adding a mention in the readme regarding the need of the coreutils `date` binary.

**Comment by rtpro** [comment]
Thanks, @genisd . I added a comment and closed the issue.
